/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.project.node;

public interface Node<A> {
    public A getValue();
    public void setValue(A value);
    public Node<A> getNext();
}
