/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.project.node;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Builder
@AllArgsConstructor
@RequiredArgsConstructor
public class StandardNode<T> implements Node<T> {
    @Setter @Getter @NonNull private T value;
    @Getter @Builder.Default private Node<T> next = null;
}
